- name: get fedora version
  shell: rpm -E %fedora
  register: fedora_version
  changed_when: false

- name: add rpmfusion repo
  yum: name={{ item }}
       state=present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm

