- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart hostapd
  service:
    name: hostapd
    state: restarted

- name: save iptables
  shell: iptables-save > /etc/iptables.rules

- name: restore iptables
  lineinfile:
    dest: /etc/rc.local
    line: iptables-restore < /etc/iptables.rules
    insertbefore: '^exit 0'