- name: "add virtualbox repo"
  copy:
    src: virtualbox.repo
    dest: /etc/yum.repos.d
    mode: 0644
    owner: root
    group: root

- name: "install binutils"
  yum:
    name: binutils
    state: latest

- name: "install dkms"
  yum:
    name: dkms
    state: latest

- name: "install gcc"
  yum:
    name: gcc
    state: latest

- name: "install glibc-devel"
  yum:
    name: glibc-devel
    state: latest

- name: "install glibc-headers"
  yum:
    name: glibc-headers
    state: latest

- name: "get current kernel name"
  shell: uname -r
  register: kernel_name

- name: "install kernel-devel"
  yum:
    name: kernel-devel-{{ kernel_name.stdout }}
    state: latest

- name: "install kernel-headers"
  yum:
    name: kernel-headers-{{ kernel_name.stdout }}
    state: latest

- name: "install libgomp"
  yum:
    name: libgomp
    state: latest

- name: "install make"
  yum:
    name: make
    state: latest

- name: "install patch"
  yum:
    name: patch
    state: latest

- name: "install qt"
  yum:
    name: qt
    state: latest

- name: "install virtualbox"
  yum:
    name: VirtualBox-5.0
    state: latest

- name: "install virtualbox kernel driver"
  shell: /etc/init.d/vboxdrv setup

