- name: "add virtualbox repo"
  copy:
    src: virtualbox.repo
    dest: /etc/yum.repos.d
    mode: 0644
    owner: root
    group: root

- name: "get current kernel name"
  shell: uname -r
  register: kernel_name
  changed_when: false

- name: "install virtualbox dependencies"
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dkms
    - gcc
    - kernel-devel-{{ kernel_name.stdout }}
    - kernel-headers-{{ kernel_name.stdout }}

- name: "install virtualbox"
  yum:
    name: VirtualBox-5.0
    state: latest

