- name: "add virtualbox repo"
  copy:
    src: virtualbox.repo
    dest: /etc/yum.repos.d
    mode: 0644
    owner: root
    group: root

- name: "get current kernel name"
  shell: uname -r
  register: kernel_name

- name: "install virtualbox dependencies"
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - binutils
    - dkms
    - gcc
    - glibc-devel
    - glibc-headers
    - kernel-devel-{{ kernel_name.stdout }}
    - kernel-headers-{{ kernel_name.stdout }}
    - libgomp
    - make
    - patch
    - qt

- name: "install virtualbox"
  yum:
    name: VirtualBox-5.0
    state: latest

- name: "check if virtualbox kernel driver is installed"
  stat: path=/lib/modules/{{ kernel_name.stdout }}/extra/vboxdrv.ko
  register: virtualbox_kernel_driver_installed

- name: "install virtualbox kernel driver"
  shell: /etc/init.d/vboxdrv setup
  when: virtualbox_kernel_driver_installed.stat.exists == false

