- name: add apt key
  apt_key:
    url: https://dev2day.de/pms/dev2day-pms.gpg.key
  when: ansible_lsb.id == 'Raspbian'

- name: add apt repository
  apt_repository:
    repo: deb https://dev2day.de/pms/ stretch main
  when: ansible_lsb.id == 'Raspbian'

- name: install plex media server
  apt:
    name: plexmediaserver-installer
    update_cache: yes

- name: create plex library folders
  file:
    dest: "{{plex_library_base_path}}/{{item}}"
    owner: plex
    group: plex
    mode: 0755
    state: directory
  with_items:
    - movies
    - tv-series
